package preview

import (
	"context"

	"github.com/paranoidi/paras-commander/internal/ui/previewpanel"
)

// MediaCache stores protocol-agnostic downscaled PNG rasters for stills and video grids.
// Display paths do a final cell-budget fit + Kitty/sixel encode from these bytes.
type MediaCache interface {
	// LoadStill returns a cached or freshly loaded still PNG (max-edge clamped) with metadata text.
	LoadStill(ctx context.Context, path string, mtime, size int64, maxEdge int, load func(context.Context) (png []byte, meta string, err error)) (png []byte, meta string, err error)
	// LoadRender returns a cached or freshly loaded final protocol-encoded payload for one exact
	// on-screen pixel box (post cell-fit resize, post Kitty/sixel encode).
	LoadRender(ctx context.Context, path string, mtime, size int64, proto previewpanel.ImageProtocol, unicodePlaceholder, inTmux bool, maxPxW, maxPxH int, load func(context.Context) (payload []byte, w, h int, err error)) (payload []byte, w, h int, err error)
	// LoadVideo returns a cached or freshly loaded video-thumb grid PNG. onProgress, if non-nil,
	// is called with each frame completed by load, even when this call joins a flight already
	// started by another caller (e.g. background prefetch) rather than running load itself.
	LoadVideo(ctx context.Context, path string, mtime, size int64, maxEdge, cols, rows int, onProgress func(done, total int), load func(context.Context, func(done, total int)) (png []byte, err error)) (png []byte, err error)
	// HasVideo reports whether a warm memory/disk hit exists for this video-thumb key.
	HasVideo(path string, mtime, size int64, maxEdge, cols, rows int) bool
	// InFlight reports whether path is currently being decoded/generated by a worker or Load*.
	InFlight(path string) bool
	// SnapshotInFlight returns absolute paths currently in flight (for the loading mark).
	SnapshotInFlight() []string
}
