package preview

import "context"

// MediaCache stores protocol-agnostic downscaled PNG rasters for stills and video grids.
// Display paths do a final cell-budget fit + Kitty/sixel encode from these bytes.
type MediaCache interface {
	// LoadStill returns a cached or freshly loaded still PNG (max-edge clamped) with metadata text.
	LoadStill(ctx context.Context, path string, mtime, size int64, maxEdge int, load func(context.Context) (png []byte, meta string, err error)) (png []byte, meta string, err error)
	// LoadVideo returns a cached or freshly loaded video-thumb grid PNG.
	LoadVideo(ctx context.Context, path string, mtime, size int64, maxEdge, cols, rows int, load func(context.Context) (png []byte, err error)) (png []byte, err error)
	// HasVideo reports whether a warm memory/disk hit exists for this video-thumb key.
	HasVideo(path string, mtime, size int64, maxEdge, cols, rows int) bool
	// InFlight reports whether path is currently being decoded/generated by a worker or Load*.
	InFlight(path string) bool
	// SnapshotInFlight returns absolute paths currently in flight (for the loading mark).
	SnapshotInFlight() []string
}
